const MODULE_NAME = 'DragableList.';

export const UPDATE_LIST = `${MODULE_NAME}UPDATE_LIST`;
export const REMOVE_FROM_LIST = `${MODULE_NAME}REMOVE_FROM_LIST`;
export const ADD_TO_LIST = `${MODULE_NAME}ADD_TO_LIST`;
export const UPDATE_TASK = `${MODULE_NAME}UPDATE_TASK`;